services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - tailscale_data:/var/lib/tailscale
    secrets:
      - ts_authkey
    depends_on:
      - nextcloud
    env_file:
      - .env
    networks:
      - private
    command: >
      sh -c "
        tailscaled --state=/var/lib/tailscale/tailscaled.state &
        sleep 3;
        tailscale up --authkey=$$(cat /run/secrets/ts_authkey) --hostname=${TS_HOSTNAME};
        tailscale serve --bg http://nextcloud:80;
        tail -f /dev/null
      "
    restart: unless-stopped

  mariadb:
    image: mariadb:11.8
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env 
    secrets:
      - db_password
      - db_root_password
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - private

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    env_file:
      - .env
    networks:
      - private

  nextcloud:
    image: nextcloud:31-apache
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    expose:
      - "80"
    env_file:
      - .env
    secrets:
      - db_password
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - private

volumes:
  tailscale_data:
  nextcloud_data:
  redis_data:

networks:
  private:

secrets:
  db_password:
    file: ./secrets/mariadb_password.txt
  db_root_password:
    file: ./secrets/mariadb_root_password.txt
  ts_authkey:
    file: ./secrets/ts_authkey.txt